# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/ronal/Documents/ECE527MPs/final_project/final_project/final_project.srcs/sources_1/bd/design_1/ip/design_1_DWT_Accel_0_16/design_1_DWT_Accel_0_16.xci
# IP: The module: 'design_1_DWT_Accel_0_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ronal/Documents/ECE527MPs/final_project/final_project/final_project.srcs/sources_1/bd/design_1/ip/design_1_DWT_Accel_0_16/constraints/DWT_Accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_DWT_Accel_0_16'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/ronal/Documents/ECE527MPs/final_project/final_project/final_project.srcs/sources_1/bd/design_1/ip/design_1_DWT_Accel_0_16/design_1_DWT_Accel_0_16.xci
# IP: The module: 'design_1_DWT_Accel_0_16' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/ronal/Documents/ECE527MPs/final_project/final_project/final_project.srcs/sources_1/bd/design_1/ip/design_1_DWT_Accel_0_16/constraints/DWT_Accel_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_DWT_Accel_0_16'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
