-- (c) Copyright 1995-2023 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
-- DO NOT MODIFY THIS FILE.

-- IP VLNV: xilinx.com:hls:DWT_Accel:1.0
-- IP Revision: 2113339032

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY design_1_DWT_Accel_0_16 IS
  PORT (
    s_axi_CTL_AWADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
    s_axi_CTL_AWVALID : IN STD_LOGIC;
    s_axi_CTL_AWREADY : OUT STD_LOGIC;
    s_axi_CTL_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_axi_CTL_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_axi_CTL_WVALID : IN STD_LOGIC;
    s_axi_CTL_WREADY : OUT STD_LOGIC;
    s_axi_CTL_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    s_axi_CTL_BVALID : OUT STD_LOGIC;
    s_axi_CTL_BREADY : IN STD_LOGIC;
    s_axi_CTL_ARADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
    s_axi_CTL_ARVALID : IN STD_LOGIC;
    s_axi_CTL_ARREADY : OUT STD_LOGIC;
    s_axi_CTL_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_axi_CTL_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    s_axi_CTL_RVALID : OUT STD_LOGIC;
    s_axi_CTL_RREADY : IN STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_DATA_A_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_A_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_A_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_A_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_A_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_A_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_A_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_A_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_A_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_A_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_A_AWREADY : IN STD_LOGIC;
    m_axi_DATA_A_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_A_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_A_WLAST : OUT STD_LOGIC;
    m_axi_DATA_A_WVALID : OUT STD_LOGIC;
    m_axi_DATA_A_WREADY : IN STD_LOGIC;
    m_axi_DATA_A_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_A_BVALID : IN STD_LOGIC;
    m_axi_DATA_A_BREADY : OUT STD_LOGIC;
    m_axi_DATA_A_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_A_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_A_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_A_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_A_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_A_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_A_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_A_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_A_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_A_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_A_ARREADY : IN STD_LOGIC;
    m_axi_DATA_A_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_A_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_A_RLAST : IN STD_LOGIC;
    m_axi_DATA_A_RVALID : IN STD_LOGIC;
    m_axi_DATA_A_RREADY : OUT STD_LOGIC;
    m_axi_DATA_B_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_B_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_B_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_B_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_B_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_B_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_B_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_B_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_B_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_B_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_B_AWREADY : IN STD_LOGIC;
    m_axi_DATA_B_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_B_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_B_WLAST : OUT STD_LOGIC;
    m_axi_DATA_B_WVALID : OUT STD_LOGIC;
    m_axi_DATA_B_WREADY : IN STD_LOGIC;
    m_axi_DATA_B_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_B_BVALID : IN STD_LOGIC;
    m_axi_DATA_B_BREADY : OUT STD_LOGIC;
    m_axi_DATA_B_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_B_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_B_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_B_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_B_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_B_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_B_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_B_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_B_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_B_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_B_ARREADY : IN STD_LOGIC;
    m_axi_DATA_B_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_B_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_B_RLAST : IN STD_LOGIC;
    m_axi_DATA_B_RVALID : IN STD_LOGIC;
    m_axi_DATA_B_RREADY : OUT STD_LOGIC;
    m_axi_DATA_C_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_C_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_C_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_C_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_C_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_C_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_C_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_C_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_C_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_C_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_C_AWREADY : IN STD_LOGIC;
    m_axi_DATA_C_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_C_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_C_WLAST : OUT STD_LOGIC;
    m_axi_DATA_C_WVALID : OUT STD_LOGIC;
    m_axi_DATA_C_WREADY : IN STD_LOGIC;
    m_axi_DATA_C_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_C_BVALID : IN STD_LOGIC;
    m_axi_DATA_C_BREADY : OUT STD_LOGIC;
    m_axi_DATA_C_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_C_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_C_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_C_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_C_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_C_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_C_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_C_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_C_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_C_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_C_ARREADY : IN STD_LOGIC;
    m_axi_DATA_C_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_C_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_C_RLAST : IN STD_LOGIC;
    m_axi_DATA_C_RVALID : IN STD_LOGIC;
    m_axi_DATA_C_RREADY : OUT STD_LOGIC
  );
END design_1_DWT_Accel_0_16;

ARCHITECTURE design_1_DWT_Accel_0_16_arch OF design_1_DWT_Accel_0_16 IS
  ATTRIBUTE DowngradeIPIdentifiedWarnings : STRING;
  ATTRIBUTE DowngradeIPIdentifiedWarnings OF design_1_DWT_Accel_0_16_arch: ARCHITECTURE IS "yes";
  COMPONENT DWT_Accel IS
    GENERIC (
      C_S_AXI_CTL_ADDR_WIDTH : INTEGER;
      C_S_AXI_CTL_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_A_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_A_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_A_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_A_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_A_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_A_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_A_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_A_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_A_USER_VALUE : INTEGER;
      C_M_AXI_DATA_A_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_A_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_B_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_B_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_B_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_B_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_B_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_B_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_B_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_B_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_B_USER_VALUE : INTEGER;
      C_M_AXI_DATA_B_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_B_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_C_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_C_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_C_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_C_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_C_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_C_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_C_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_C_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_C_USER_VALUE : INTEGER;
      C_M_AXI_DATA_C_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_C_CACHE_VALUE : INTEGER
    );
    PORT (
      s_axi_CTL_AWADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
      s_axi_CTL_AWVALID : IN STD_LOGIC;
      s_axi_CTL_AWREADY : OUT STD_LOGIC;
      s_axi_CTL_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_axi_CTL_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_axi_CTL_WVALID : IN STD_LOGIC;
      s_axi_CTL_WREADY : OUT STD_LOGIC;
      s_axi_CTL_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      s_axi_CTL_BVALID : OUT STD_LOGIC;
      s_axi_CTL_BREADY : IN STD_LOGIC;
      s_axi_CTL_ARADDR : IN STD_LOGIC_VECTOR(5 DOWNTO 0);
      s_axi_CTL_ARVALID : IN STD_LOGIC;
      s_axi_CTL_ARREADY : OUT STD_LOGIC;
      s_axi_CTL_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_axi_CTL_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      s_axi_CTL_RVALID : OUT STD_LOGIC;
      s_axi_CTL_RREADY : IN STD_LOGIC;
      ap_clk : IN STD_LOGIC;
      ap_rst_n : IN STD_LOGIC;
      interrupt : OUT STD_LOGIC;
      m_axi_DATA_A_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_A_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_A_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_A_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_A_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_A_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_A_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_A_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_A_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_A_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_A_AWREADY : IN STD_LOGIC;
      m_axi_DATA_A_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_A_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_A_WLAST : OUT STD_LOGIC;
      m_axi_DATA_A_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_WVALID : OUT STD_LOGIC;
      m_axi_DATA_A_WREADY : IN STD_LOGIC;
      m_axi_DATA_A_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_A_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_BVALID : IN STD_LOGIC;
      m_axi_DATA_A_BREADY : OUT STD_LOGIC;
      m_axi_DATA_A_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_A_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_A_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_A_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_A_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_A_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_A_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_A_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_A_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_A_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_A_ARREADY : IN STD_LOGIC;
      m_axi_DATA_A_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_A_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_A_RLAST : IN STD_LOGIC;
      m_axi_DATA_A_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_A_RVALID : IN STD_LOGIC;
      m_axi_DATA_A_RREADY : OUT STD_LOGIC;
      m_axi_DATA_B_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_B_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_B_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_B_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_B_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_B_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_B_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_B_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_B_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_B_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_B_AWREADY : IN STD_LOGIC;
      m_axi_DATA_B_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_B_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_B_WLAST : OUT STD_LOGIC;
      m_axi_DATA_B_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_WVALID : OUT STD_LOGIC;
      m_axi_DATA_B_WREADY : IN STD_LOGIC;
      m_axi_DATA_B_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_B_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_BVALID : IN STD_LOGIC;
      m_axi_DATA_B_BREADY : OUT STD_LOGIC;
      m_axi_DATA_B_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_B_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_B_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_B_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_B_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_B_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_B_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_B_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_B_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_B_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_B_ARREADY : IN STD_LOGIC;
      m_axi_DATA_B_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_B_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_B_RLAST : IN STD_LOGIC;
      m_axi_DATA_B_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_B_RVALID : IN STD_LOGIC;
      m_axi_DATA_B_RREADY : OUT STD_LOGIC;
      m_axi_DATA_C_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_C_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_C_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_C_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_C_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_C_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_C_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_C_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_C_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_C_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_C_AWREADY : IN STD_LOGIC;
      m_axi_DATA_C_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_WDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_C_WSTRB : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_C_WLAST : OUT STD_LOGIC;
      m_axi_DATA_C_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_WVALID : OUT STD_LOGIC;
      m_axi_DATA_C_WREADY : IN STD_LOGIC;
      m_axi_DATA_C_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_C_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_BVALID : IN STD_LOGIC;
      m_axi_DATA_C_BREADY : OUT STD_LOGIC;
      m_axi_DATA_C_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_C_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_C_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_C_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_C_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_C_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_C_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_C_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_C_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_C_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_C_ARREADY : IN STD_LOGIC;
      m_axi_DATA_C_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_RDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_C_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_C_RLAST : IN STD_LOGIC;
      m_axi_DATA_C_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_C_RVALID : IN STD_LOGIC;
      m_axi_DATA_C_RREADY : OUT STD_LOGIC
    );
  END COMPONENT DWT_Accel;
  ATTRIBUTE IP_DEFINITION_SOURCE : STRING;
  ATTRIBUTE IP_DEFINITION_SOURCE OF design_1_DWT_Accel_0_16_arch: ARCHITECTURE IS "HLS";
  ATTRIBUTE X_INTERFACE_INFO : STRING;
  ATTRIBUTE X_INTERFACE_PARAMETER : STRING;
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_C_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_C, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.000, CLK_DOMAI" & 
"N design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_C_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_C AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_B_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_B, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.000, CLK_DOMAI" & 
"N design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_B_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_B AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_A_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_A, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 32, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.000, CLK_DOMAI" & 
"N design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_A_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_A AWADDR";
  ATTRIBUTE X_INTERFACE_PARAMETER OF interrupt: SIGNAL IS "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  ATTRIBUTE X_INTERFACE_INFO OF interrupt: SIGNAL IS "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  ATTRIBUTE X_INTERFACE_PARAMETER OF ap_rst_n: SIGNAL IS "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF ap_rst_n: SIGNAL IS "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  ATTRIBUTE X_INTERFACE_PARAMETER OF ap_clk: SIGNAL IS "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_CTL:m_axi_DATA_A:m_axi_DATA_B:m_axi_DATA_C, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000, PHASE 0.000, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF ap_clk: SIGNAL IS "xilinx.com:signal:clock:1.0 ap_clk CLK";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL AWVALID";
  ATTRIBUTE X_INTERFACE_PARAMETER OF s_axi_CTL_AWADDR: SIGNAL IS "XIL_INTERFACENAME s_axi_CTL, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.000, CLK_DOMAIN design_1_processing_system7_0_0_FCLK_CLK0, NUM_READ_THR" & 
"EADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTL_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTL AWADDR";
BEGIN
  U0 : DWT_Accel
    GENERIC MAP (
      C_S_AXI_CTL_ADDR_WIDTH => 6,
      C_S_AXI_CTL_DATA_WIDTH => 32,
      C_M_AXI_DATA_A_ID_WIDTH => 1,
      C_M_AXI_DATA_A_ADDR_WIDTH => 32,
      C_M_AXI_DATA_A_DATA_WIDTH => 32,
      C_M_AXI_DATA_A_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_A_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_A_WUSER_WIDTH => 1,
      C_M_AXI_DATA_A_RUSER_WIDTH => 1,
      C_M_AXI_DATA_A_BUSER_WIDTH => 1,
      C_M_AXI_DATA_A_USER_VALUE => 0,
      C_M_AXI_DATA_A_PROT_VALUE => 0,
      C_M_AXI_DATA_A_CACHE_VALUE => 3,
      C_M_AXI_DATA_B_ID_WIDTH => 1,
      C_M_AXI_DATA_B_ADDR_WIDTH => 32,
      C_M_AXI_DATA_B_DATA_WIDTH => 32,
      C_M_AXI_DATA_B_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_B_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_B_WUSER_WIDTH => 1,
      C_M_AXI_DATA_B_RUSER_WIDTH => 1,
      C_M_AXI_DATA_B_BUSER_WIDTH => 1,
      C_M_AXI_DATA_B_USER_VALUE => 0,
      C_M_AXI_DATA_B_PROT_VALUE => 0,
      C_M_AXI_DATA_B_CACHE_VALUE => 3,
      C_M_AXI_DATA_C_ID_WIDTH => 1,
      C_M_AXI_DATA_C_ADDR_WIDTH => 32,
      C_M_AXI_DATA_C_DATA_WIDTH => 32,
      C_M_AXI_DATA_C_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_C_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_C_WUSER_WIDTH => 1,
      C_M_AXI_DATA_C_RUSER_WIDTH => 1,
      C_M_AXI_DATA_C_BUSER_WIDTH => 1,
      C_M_AXI_DATA_C_USER_VALUE => 0,
      C_M_AXI_DATA_C_PROT_VALUE => 0,
      C_M_AXI_DATA_C_CACHE_VALUE => 3
    )
    PORT MAP (
      s_axi_CTL_AWADDR => s_axi_CTL_AWADDR,
      s_axi_CTL_AWVALID => s_axi_CTL_AWVALID,
      s_axi_CTL_AWREADY => s_axi_CTL_AWREADY,
      s_axi_CTL_WDATA => s_axi_CTL_WDATA,
      s_axi_CTL_WSTRB => s_axi_CTL_WSTRB,
      s_axi_CTL_WVALID => s_axi_CTL_WVALID,
      s_axi_CTL_WREADY => s_axi_CTL_WREADY,
      s_axi_CTL_BRESP => s_axi_CTL_BRESP,
      s_axi_CTL_BVALID => s_axi_CTL_BVALID,
      s_axi_CTL_BREADY => s_axi_CTL_BREADY,
      s_axi_CTL_ARADDR => s_axi_CTL_ARADDR,
      s_axi_CTL_ARVALID => s_axi_CTL_ARVALID,
      s_axi_CTL_ARREADY => s_axi_CTL_ARREADY,
      s_axi_CTL_RDATA => s_axi_CTL_RDATA,
      s_axi_CTL_RRESP => s_axi_CTL_RRESP,
      s_axi_CTL_RVALID => s_axi_CTL_RVALID,
      s_axi_CTL_RREADY => s_axi_CTL_RREADY,
      ap_clk => ap_clk,
      ap_rst_n => ap_rst_n,
      interrupt => interrupt,
      m_axi_DATA_A_AWADDR => m_axi_DATA_A_AWADDR,
      m_axi_DATA_A_AWLEN => m_axi_DATA_A_AWLEN,
      m_axi_DATA_A_AWSIZE => m_axi_DATA_A_AWSIZE,
      m_axi_DATA_A_AWBURST => m_axi_DATA_A_AWBURST,
      m_axi_DATA_A_AWLOCK => m_axi_DATA_A_AWLOCK,
      m_axi_DATA_A_AWREGION => m_axi_DATA_A_AWREGION,
      m_axi_DATA_A_AWCACHE => m_axi_DATA_A_AWCACHE,
      m_axi_DATA_A_AWPROT => m_axi_DATA_A_AWPROT,
      m_axi_DATA_A_AWQOS => m_axi_DATA_A_AWQOS,
      m_axi_DATA_A_AWVALID => m_axi_DATA_A_AWVALID,
      m_axi_DATA_A_AWREADY => m_axi_DATA_A_AWREADY,
      m_axi_DATA_A_WDATA => m_axi_DATA_A_WDATA,
      m_axi_DATA_A_WSTRB => m_axi_DATA_A_WSTRB,
      m_axi_DATA_A_WLAST => m_axi_DATA_A_WLAST,
      m_axi_DATA_A_WVALID => m_axi_DATA_A_WVALID,
      m_axi_DATA_A_WREADY => m_axi_DATA_A_WREADY,
      m_axi_DATA_A_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_A_BRESP => m_axi_DATA_A_BRESP,
      m_axi_DATA_A_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_A_BVALID => m_axi_DATA_A_BVALID,
      m_axi_DATA_A_BREADY => m_axi_DATA_A_BREADY,
      m_axi_DATA_A_ARADDR => m_axi_DATA_A_ARADDR,
      m_axi_DATA_A_ARLEN => m_axi_DATA_A_ARLEN,
      m_axi_DATA_A_ARSIZE => m_axi_DATA_A_ARSIZE,
      m_axi_DATA_A_ARBURST => m_axi_DATA_A_ARBURST,
      m_axi_DATA_A_ARLOCK => m_axi_DATA_A_ARLOCK,
      m_axi_DATA_A_ARREGION => m_axi_DATA_A_ARREGION,
      m_axi_DATA_A_ARCACHE => m_axi_DATA_A_ARCACHE,
      m_axi_DATA_A_ARPROT => m_axi_DATA_A_ARPROT,
      m_axi_DATA_A_ARQOS => m_axi_DATA_A_ARQOS,
      m_axi_DATA_A_ARVALID => m_axi_DATA_A_ARVALID,
      m_axi_DATA_A_ARREADY => m_axi_DATA_A_ARREADY,
      m_axi_DATA_A_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_A_RDATA => m_axi_DATA_A_RDATA,
      m_axi_DATA_A_RRESP => m_axi_DATA_A_RRESP,
      m_axi_DATA_A_RLAST => m_axi_DATA_A_RLAST,
      m_axi_DATA_A_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_A_RVALID => m_axi_DATA_A_RVALID,
      m_axi_DATA_A_RREADY => m_axi_DATA_A_RREADY,
      m_axi_DATA_B_AWADDR => m_axi_DATA_B_AWADDR,
      m_axi_DATA_B_AWLEN => m_axi_DATA_B_AWLEN,
      m_axi_DATA_B_AWSIZE => m_axi_DATA_B_AWSIZE,
      m_axi_DATA_B_AWBURST => m_axi_DATA_B_AWBURST,
      m_axi_DATA_B_AWLOCK => m_axi_DATA_B_AWLOCK,
      m_axi_DATA_B_AWREGION => m_axi_DATA_B_AWREGION,
      m_axi_DATA_B_AWCACHE => m_axi_DATA_B_AWCACHE,
      m_axi_DATA_B_AWPROT => m_axi_DATA_B_AWPROT,
      m_axi_DATA_B_AWQOS => m_axi_DATA_B_AWQOS,
      m_axi_DATA_B_AWVALID => m_axi_DATA_B_AWVALID,
      m_axi_DATA_B_AWREADY => m_axi_DATA_B_AWREADY,
      m_axi_DATA_B_WDATA => m_axi_DATA_B_WDATA,
      m_axi_DATA_B_WSTRB => m_axi_DATA_B_WSTRB,
      m_axi_DATA_B_WLAST => m_axi_DATA_B_WLAST,
      m_axi_DATA_B_WVALID => m_axi_DATA_B_WVALID,
      m_axi_DATA_B_WREADY => m_axi_DATA_B_WREADY,
      m_axi_DATA_B_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_B_BRESP => m_axi_DATA_B_BRESP,
      m_axi_DATA_B_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_B_BVALID => m_axi_DATA_B_BVALID,
      m_axi_DATA_B_BREADY => m_axi_DATA_B_BREADY,
      m_axi_DATA_B_ARADDR => m_axi_DATA_B_ARADDR,
      m_axi_DATA_B_ARLEN => m_axi_DATA_B_ARLEN,
      m_axi_DATA_B_ARSIZE => m_axi_DATA_B_ARSIZE,
      m_axi_DATA_B_ARBURST => m_axi_DATA_B_ARBURST,
      m_axi_DATA_B_ARLOCK => m_axi_DATA_B_ARLOCK,
      m_axi_DATA_B_ARREGION => m_axi_DATA_B_ARREGION,
      m_axi_DATA_B_ARCACHE => m_axi_DATA_B_ARCACHE,
      m_axi_DATA_B_ARPROT => m_axi_DATA_B_ARPROT,
      m_axi_DATA_B_ARQOS => m_axi_DATA_B_ARQOS,
      m_axi_DATA_B_ARVALID => m_axi_DATA_B_ARVALID,
      m_axi_DATA_B_ARREADY => m_axi_DATA_B_ARREADY,
      m_axi_DATA_B_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_B_RDATA => m_axi_DATA_B_RDATA,
      m_axi_DATA_B_RRESP => m_axi_DATA_B_RRESP,
      m_axi_DATA_B_RLAST => m_axi_DATA_B_RLAST,
      m_axi_DATA_B_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_B_RVALID => m_axi_DATA_B_RVALID,
      m_axi_DATA_B_RREADY => m_axi_DATA_B_RREADY,
      m_axi_DATA_C_AWADDR => m_axi_DATA_C_AWADDR,
      m_axi_DATA_C_AWLEN => m_axi_DATA_C_AWLEN,
      m_axi_DATA_C_AWSIZE => m_axi_DATA_C_AWSIZE,
      m_axi_DATA_C_AWBURST => m_axi_DATA_C_AWBURST,
      m_axi_DATA_C_AWLOCK => m_axi_DATA_C_AWLOCK,
      m_axi_DATA_C_AWREGION => m_axi_DATA_C_AWREGION,
      m_axi_DATA_C_AWCACHE => m_axi_DATA_C_AWCACHE,
      m_axi_DATA_C_AWPROT => m_axi_DATA_C_AWPROT,
      m_axi_DATA_C_AWQOS => m_axi_DATA_C_AWQOS,
      m_axi_DATA_C_AWVALID => m_axi_DATA_C_AWVALID,
      m_axi_DATA_C_AWREADY => m_axi_DATA_C_AWREADY,
      m_axi_DATA_C_WDATA => m_axi_DATA_C_WDATA,
      m_axi_DATA_C_WSTRB => m_axi_DATA_C_WSTRB,
      m_axi_DATA_C_WLAST => m_axi_DATA_C_WLAST,
      m_axi_DATA_C_WVALID => m_axi_DATA_C_WVALID,
      m_axi_DATA_C_WREADY => m_axi_DATA_C_WREADY,
      m_axi_DATA_C_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_C_BRESP => m_axi_DATA_C_BRESP,
      m_axi_DATA_C_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_C_BVALID => m_axi_DATA_C_BVALID,
      m_axi_DATA_C_BREADY => m_axi_DATA_C_BREADY,
      m_axi_DATA_C_ARADDR => m_axi_DATA_C_ARADDR,
      m_axi_DATA_C_ARLEN => m_axi_DATA_C_ARLEN,
      m_axi_DATA_C_ARSIZE => m_axi_DATA_C_ARSIZE,
      m_axi_DATA_C_ARBURST => m_axi_DATA_C_ARBURST,
      m_axi_DATA_C_ARLOCK => m_axi_DATA_C_ARLOCK,
      m_axi_DATA_C_ARREGION => m_axi_DATA_C_ARREGION,
      m_axi_DATA_C_ARCACHE => m_axi_DATA_C_ARCACHE,
      m_axi_DATA_C_ARPROT => m_axi_DATA_C_ARPROT,
      m_axi_DATA_C_ARQOS => m_axi_DATA_C_ARQOS,
      m_axi_DATA_C_ARVALID => m_axi_DATA_C_ARVALID,
      m_axi_DATA_C_ARREADY => m_axi_DATA_C_ARREADY,
      m_axi_DATA_C_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_C_RDATA => m_axi_DATA_C_RDATA,
      m_axi_DATA_C_RRESP => m_axi_DATA_C_RRESP,
      m_axi_DATA_C_RLAST => m_axi_DATA_C_RLAST,
      m_axi_DATA_C_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_C_RVALID => m_axi_DATA_C_RVALID,
      m_axi_DATA_C_RREADY => m_axi_DATA_C_RREADY
    );
END design_1_DWT_Accel_0_16_arch;
